function status = TestGurobi()

TorF = exist('gurobi', 'file') == 3;
if TorF
    try
        model = struct( ...
            'A', sparse(1), ...
            'rhs', 1, ...
            'sense', '=', ...
            'vtype', 'C', ...
            'obj', 1, ...
            'modelsense', 'min' ...
            );
        params = struct( ...
            'outputflag', 0 ...
            );
        env = struct('CloudPool','232163-pool2');
        result = gurobi(model, params, env);
        disp(['Job Status: ', result.status]);
        status = result.status
    catch e  % gurobiError
        TorF = 0;
        disp('Gurobi Error!');
        disp(e)
    end
end

end