# Run pylint on powersimdata directory
# docker run -it --rm \
# -v (pwd):/app \
# --name pylint 
# powersimdata:lint

FROM python:3.8.3-buster

RUN apt-get update && apt-get install -y libblas-dev liblapack-dev gfortran
WORKDIR /app
RUN pip install pylint

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["pylint", "powersimdata"]

