col_name_branch = [
    "from_bus_id",
    "to_bus_id",
    "r",
    "x",
    "b",
    "rateA",
    "rateB",
    "rateC",
    "ratio",
    "angle",
    "status",
    "angmin",
    "angmax",
    "Pf",
    "Qf",
    "Pt",
    "Qt",
    "mu_Sf",
    "mu_St",
    "mu_angmin",
    "mu_angmax",
]
col_type_branch = [
    "int",
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
]

col_name_bus = [
    "bus_id",
    "type",
    "Pd",
    "Qd",
    "Gs",
    "Bs",
    "zone_id",
    "Vm",
    "Va",
    "baseKV",
    "loss_zone",
    "Vmax",
    "Vmin",
    "lam_P",
    "lam_Q",
    "mu_Vmax",
    "mu_Vmin",
]
col_type_bus = [
    "int",
    "int",
    "float",
    "float",
    "float",
    "float",
    "int",
    "float",
    "float",
    "float",
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
]

col_name_bus2sub = ["sub_id", "interconnect"]
col_type_bus2sub = ["int", "str"]

col_name_dcline = [
    "from_bus_id",
    "to_bus_id",
    "status",
    "Pf",
    "Pt",
    "Qf",
    "Qt",
    "Vf",
    "Vt",
    "Pmin",
    "Pmax",
    "QminF",
    "QmaxF",
    "QminT",
    "QmaxT",
    "loss0",
    "loss1",
    "muPmin",
    "muPmax",
    "muQminF",
    "muQmaxF",
    "muQminT",
    "muQmaxT",
]
col_type_dcline = [
    "int",
    "int",
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
]

col_name_gencost = ["type", "startup", "shutdown", "n", "c2", "c1", "c0"]
col_type_gencost = ["int", "float", "float", "int", "float", "float", "float"]

col_name_heat_rate_curve = ["GenIOB", "GenIOC", "GenIOD"]
col_type_heat_rate_curve = ["float", "float", "float"]


col_name_plant = [
    "bus_id",
    "Pg",
    "Qg",
    "Qmax",
    "Qmin",
    "Vg",
    "mBase",
    "status",
    "Pmax",
    "Pmin",
    "Pc1",
    "Pc2",
    "Qc1min",
    "Qc1max",
    "Qc2min",
    "Qc2max",
    "ramp_agc",
    "ramp_10",
    "ramp_30",
    "ramp_q",
    "apf",
    "mu_Pmax",
    "mu_Pmin",
    "mu_Qmax",
    "mu_Qmin",
]
col_type_plant = [
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
]

col_name_storage_storagedata = [
    "UnitIdx",
    "InitialStorage",
    "InitialStorageLowerBound",
    "InitialStorageUpperBound",
    "InitialStorageCost",
    "TerminalStoragePrice",
    "MinStorageLevel",
    "MaxStorageLevel",
    "OutEff",
    "InEff",
    "LossFactor",
    "rho",
    "ExpectedTerminalStorageMax",
    "ExpectedTerminalStorageMin",
]
col_type_storage_storagedata = [
    "int",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
    "float",
]

col_name_sub = ["name", "interconnect_sub_id", "lat", "lon", "interconnect"]
col_type_sub = ["str", "int", "float", "float", "str"]
