name: Run tox

on: [push]

jobs:
  ci:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            toxenv: ['pytest-ci', 'checkformatting']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Start postgres container
        if: ${{ matrix.toxenv == 'pytest-ci' }}
        run: |
          docker-compose -f stack.yml up -d
          while ! nc -z localhost 5432; do sleep 1; done;
        working-directory: powersimdata/data_access
      - name: Run tox
        run: |
          tox -e ${{ matrix.toxenv }}
