name: Code coverage

on:
  push:
    branches:
      - 'develop'

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: Generate coverage report
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Start postgres container
        run: |
          docker-compose -f stack.yml up -d
          while ! nc -z localhost 5432; do sleep 1; done;
        working-directory: powersimdata/data_access

      - run: python -m pip install --upgrade pip tox
      - run: tox -e pytest-ci -- --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-powersimdata
          fail_ci_if_error: true
