name: Trigger external workflows

on:
  push:

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish docs website
        uses: Breakthrough-Energy/actions/workflow-trigger@main
        with:
          repo: docs
          branch: master
          workflow_id: 2386877
          token: 123

      - name: Build and publish docker image
        uses: Breakthrough-Energy/actions/workflow-trigger@main
        with:
          repo: plug
          workflow_id: 12413223
          token: 123
