name: Lint

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  formatting:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade tox
      - run: tox -e checkformatting
  flake8:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade tox
      - run: tox -e flake8
